# Generated by Django 4.1.7 on 2023-03-30 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complication",
            old_name="name",
            new_name="description",
        ),
    ]
