# Generated by Django 4.1.7 on 2023-03-30 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_rename_name_complication_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complication",
            name="vaccination",
        ),
    ]
