# Generated by Django 4.1.7 on 2023-03-30 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_remove_complication_vaccination"),
    ]

    operations = [
        migrations.AddField(
            model_name="complication",
            name="vaccination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complications",
                to="tracker.vaccination",
            ),
            preserve_default=False,
        ),
    ]
