# Generated by Django 4.1.7 on 2023-03-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_complication_vaccination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complication",
            name="description",
            field=models.CharField(max_length=50),
        ),
    ]
